# Criando dataset da empresa

In [2]:
import pandas as pd 
import numpy as np
import datetime as dt

Criando identificador dos caminhões.

In [4]:

ids = [f"10{str(i).zfill(2)}" for i in range(1, 101)]

veiculo = pd.DataFrame({"Número_caminhao": ids})

In [5]:
veiculo.head()

  Número_caminhao
0            1001
1            1002
2            1003
3            1004
4            1005

In [6]:
veiculo.tail()

   Número_caminhao
95            1096
96            1097
97            1098
98            1099
99           10100

Verificando o tipo de dado da coluna

In [8]:
veiculo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Número_caminhao  100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes

In [9]:
marcas = ['Scania', 'Mercedes', 'Volvo']
veiculo['marca'] = np.random.choice(marcas, size=len(veiculo))

In [10]:
veiculo.head()

  Número_caminhao   marca
0            1001  Scania
1            1002  Scania
2            1003   Volvo
3            1004   Volvo
4            1005   Volvo

In [11]:
veiculo.tail()

   Número_caminhao  marca
95            1096  Volvo
96            1097  Volvo
97            1098  Volvo
98            1099  Volvo
99           10100  Volvo

In [12]:
start = pd.to_datetime("2012-01-01")
end = pd.to_datetime("2023-12-31")

n = len(veiculo)

random_dates = start + (end - start) * np.random.rand(n)

veiculo['Ano'] = random_dates

In [13]:
veiculo.head()

  Número_caminhao   marca                           Ano
0            1001  Scania 2020-12-25 06:34:51.846885376
1            1002  Scania 2014-06-25 00:52:02.320067616
2            1003   Volvo 2018-03-22 09:36:56.886220224
3            1004   Volvo 2014-02-20 17:59:26.350950440
4            1005   Volvo 2019-01-11 19:55:18.981060000

In [14]:
veiculo.tail()

   Número_caminhao  marca                           Ano
95            1096  Volvo 2020-04-18 20:18:21.808443712
96            1097  Volvo 2016-03-03 17:57:30.336044912
97            1098  Volvo 2022-01-18 11:01:44.964011968
98            1099  Volvo 2019-04-23 15:33:30.052922944
99           10100  Volvo 2018-03-07 20:03:30.474602112

In [15]:
ano_de_fabricação = pd.to_datetime(veiculo['Ano']).dt.year

In [16]:
ano_de_fabricação

0     2020
1     2014
2     2018
3     2014
4     2019
      ...
95    2020
96    2016
97    2022
98    2019
99    2018
Name: Ano, Length: 100, dtype: int32

In [17]:
km = []
for ano in ano_de_fabricação:
    if ano <= 2014:
        km.append(np.random.randint(600000, 900000))
    elif ano <= 2018:
        km.append(np.random.randint(300000, 600000))
    else:
        km.append(np.random.randint(50000, 300000)) 
veiculo['Km_rodados'] = km

In [18]:
veiculo.head()

  Número_caminhao   marca                           Ano  Km_rodados
0            1001  Scania 2020-12-25 06:34:51.846885376      245939
1            1002  Scania 2014-06-25 00:52:02.320067616      829376
2            1003   Volvo 2018-03-22 09:36:56.886220224      398194
3            1004   Volvo 2014-02-20 17:59:26.350950440      872091
4            1005   Volvo 2019-01-11 19:55:18.981060000      118410

In [19]:
tipo = ['rígido', 'articulado']

veiculo['tipo'] = np.random.choice(tipo, size=len(veiculo))

In [20]:
veiculo.head()

,Número_caminhao,marca,Ano,Km_rodados,tipo
0,1001,Scania,2020-12-25 06:34:51.846885376,245939,rígido
1,1002,Scania,2014-06-25 00:52:02.320067616,829376,articulado
2,1003,Volvo,2018-03-22 09:36:56.886220224,398194,rígido
3,1004,Volvo,2014-02-20 17:59:26.350950440,872091,articulado
4,1005,Volvo,2019-01-11 19:55:18.981060000,118410,articulado

In [21]:
veiculo.to_csv("C:/Users/mathe/Documents/projetos/Analise de dados/projeto-20/paranaiba-transportes/dataset/veiculos.csv", index=False)

In [22]:
Número_caminhao = veiculo['Número_caminhao']

In [23]:
rotas_lista = [
    'Uberlândia-São_Paulo',
    'Uberlândia-Belo_Horizonte',
    'Uberlândia-Brasília',
    'Uberlândia-Goiânia',
    'Uberlândia-Rio_de_Janeiro',
    'Uberlândia-Uberaba',
    'Uberlândia-Araguari',
    'Uberlândia-Catalão',
    'Uberlândia-Ribeirão_Preto'
]

In [24]:
rotas = pd.DataFrame({'Número_Caminhão': Número_caminhao})

In [25]:
rotas.head()

  Número_Caminhão
0            1001
1            1002
2            1003
3            1004
4            1005

In [26]:
rotas['rotas'] = np.random.choice(rotas_lista, size=len(rotas))

In [27]:
rotas.head()

  Número_Caminhão                      rotas
0            1001  Uberlândia-Rio_de_Janeiro
1            1002  Uberlândia-Belo_Horizonte
2            1003  Uberlândia-Rio_de_Janeiro
3            1004         Uberlândia-Uberaba
4            1005  Uberlândia-Belo_Horizonte

In [28]:
rotas.tail()

   Número_Caminhão                      rotas
95            1096  Uberlândia-Rio_de_Janeiro
96            1097       Uberlândia-São_Paulo
97            1098        Uberlândia-Brasília
98            1099  Uberlândia-Ribeirão_Preto
99           10100        Uberlândia-Araguari

In [29]:
distancias = {   
    'Uberlândia-São_Paulo':585,
    'Uberlândia-Belo_Horizonte':540,
    'Uberlândia-Brasília':430,
    'Uberlândia-Goiânia':330,
    'Uberlândia-Rio_de_Janeiro':985,
    'Uberlândia-Uberaba':110,
    'Uberlândia-Araguari':30,
    'Uberlândia-Catalão':190,
    'Uberlândia-Ribeirão_Preto': 300
}

In [30]:
rotas['Distância_km'] = rotas['rotas'].map(distancias)

In [31]:
rotas.head()

  Número_Caminhão                      rotas  Distância_km
0            1001  Uberlândia-Rio_de_Janeiro           985
1            1002  Uberlândia-Belo_Horizonte           540
2            1003  Uberlândia-Rio_de_Janeiro           985
3            1004         Uberlândia-Uberaba           110
4            1005  Uberlândia-Belo_Horizonte           540

In [32]:
rotas.tail()

   Número_Caminhão                      rotas  Distância_km
95            1096  Uberlândia-Rio_de_Janeiro           985
96            1097       Uberlândia-São_Paulo           585
97            1098        Uberlândia-Brasília           430
98            1099  Uberlândia-Ribeirão_Preto           300
99           10100        Uberlândia-Araguari            30

In [33]:
velocidade_media = 80
rotas['Tempo_estimado_horas'] = rotas['Distância_km'] / velocidade_media

In [34]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas
0,1001,Uberlândia-Rio_de_Janeiro,985,12.3125
1,1002,Uberlândia-Belo_Horizonte,540,6.7500
2,1003,Uberlândia-Rio_de_Janeiro,985,12.3125
3,1004,Uberlândia-Uberaba,110,1.3750
4,1005,Uberlândia-Belo_Horizonte,540,6.7500

In [35]:
rotas.tail()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas
95,1096,Uberlândia-Rio_de_Janeiro,985,12.3125
96,1097,Uberlândia-São_Paulo,585,7.3125
97,1098,Uberlândia-Brasília,430,5.3750
98,1099,Uberlândia-Ribeirão_Preto,300,3.7500
99,10100,Uberlândia-Araguari,30,0.3750

In [36]:
tipo_de_carga = ['agrícola', 'industrial', 'consumo']

In [37]:
rotas['Tipo_De_Carga'] = np.random.choice(tipo_de_carga, size=len(rotas))

In [38]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas,Tipo_De_Carga
0,1001,Uberlândia-Rio_de_Janeiro,985,12.3125,industrial
1,1002,Uberlândia-Belo_Horizonte,540,6.7500,agrícola
2,1003,Uberlândia-Rio_de_Janeiro,985,12.3125,consumo
3,1004,Uberlândia-Uberaba,110,1.3750,consumo
4,1005,Uberlândia-Belo_Horizonte,540,6.7500,agrícola

In [39]:
frequencia = ['díaria', 'semanal', 'mensal']

In [40]:
rotas['Frequência'] = np.random.choice(frequencia, size=len(rotas))

In [41]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas,Tipo_De_Carga,Frequência
0,1001,Uberlândia-Rio_de_Janeiro,985,12.3125,industrial,semanal
1,1002,Uberlândia-Belo_Horizonte,540,6.7500,agrícola,díaria
2,1003,Uberlândia-Rio_de_Janeiro,985,12.3125,consumo,díaria
3,1004,Uberlândia-Uberaba,110,1.3750,consumo,díaria
4,1005,Uberlândia-Belo_Horizonte,540,6.7500,agrícola,díaria

In [42]:
rotas.to_csv('C:/Users/mathe/Documents/projetos/Analise de dados/projeto-20/paranaiba-transportes/dataset/rotas.csv')

In [43]:
produtos_list = [
    'glp', 
    'Disel', 
    'Gasolina', 
    'soja',
    'milho',
    'café',
    'eletrônicos',
    'Carnes',
    'Queijo'
]

In [44]:
n_entregas = 1000

In [45]:
entregas = pd.DataFrame({"Produtos": np.random.choice(produtos_list, size=n_entregas)})

In [46]:
entregas['id_entrega'] = range(1, n_entregas + 1)

cols = ['id_entrega'] + [col for col in entregas.columns if col != 'id_entrega']
entregas = entregas[cols]

In [47]:
entregas.head()

   id_entrega     Produtos
0           1        milho
1           2  eletrônicos
2           3        Disel
3           4     Gasolina
4           5     Gasolina

In [48]:
entregas.tail()

     id_entrega     Produtos
995         996        Disel
996         997       Queijo
997         998         soja
998         999  eletrônicos
999        1000  eletrônicos

In [49]:
start = pd.to_datetime('2020-01-01')
end = pd.to_datetime('2025-12-31')

random_entregas_dates = start + (end - start) * np.random.rand(n_entregas) 

entregas['Data_da_entrega'] = pd.to_datetime(random_entregas_dates).normalize()

In [50]:
entregas.head()

   id_entrega     Produtos Data_da_entrega
0           1        milho      2025-08-18
1           2  eletrônicos      2025-06-02
2           3        Disel      2024-08-20
3           4     Gasolina      2020-12-23
4           5     Gasolina      2024-10-25

In [51]:
entregas.tail()

     id_entrega     Produtos Data_da_entrega
995         996        Disel      2023-01-09
996         997       Queijo      2021-06-22
997         998         soja      2022-05-06
998         999  eletrônicos      2025-02-12
999        1000  eletrônicos      2025-01-24

In [52]:
status_lista = ['A tempo', 'Atrasado']
entregas['Status'] = np.random.choice(status_lista, size = len(entregas))

In [53]:
entregas.head()

   id_entrega     Produtos Data_da_entrega   Status
0           1        milho      2025-08-18  A tempo
1           2  eletrônicos      2025-06-02  A tempo
2           3        Disel      2024-08-20  A tempo
3           4     Gasolina      2020-12-23  A tempo
4           5     Gasolina      2024-10-25  A tempo

In [54]:
entregas.tail()

     id_entrega     Produtos Data_da_entrega    Status
995         996        Disel      2023-01-09   A tempo
996         997       Queijo      2021-06-22   A tempo
997         998         soja      2022-05-06  Atrasado
998         999  eletrônicos      2025-02-12   A tempo
999        1000  eletrônicos      2025-01-24  Atrasado

In [55]:
entregas.head()

   id_entrega     Produtos Data_da_entrega   Status
0           1        milho      2025-08-18  A tempo
1           2  eletrônicos      2025-06-02  A tempo
2           3        Disel      2024-08-20  A tempo
3           4     Gasolina      2020-12-23  A tempo
4           5     Gasolina      2024-10-25  A tempo

In [58]:
entregas['Destino'] = np.random.choice(rotas_lista, size = len(entregas))

In [60]:
entregas.head()

   id_entrega     Produtos Data_da_entrega   Status                    Destino
0           1        milho      2025-08-18  A tempo  Uberlândia-Ribeirão_Preto
1           2  eletrônicos      2025-06-02  A tempo        Uberlândia-Araguari
2           3        Disel      2024-08-20  A tempo       Uberlândia-São_Paulo
3           4     Gasolina      2020-12-23  A tempo  Uberlândia-Belo_Horizonte
4           5     Gasolina      2024-10-25  A tempo         Uberlândia-Goiânia

In [62]:
entregas.tail()

,id_entrega,Produtos,Data_da_entrega,Status,Destino
995,996,Disel,2023-01-09,A tempo,Uberlândia-Brasília
996,997,Queijo,2021-06-22,A tempo,Uberlândia-Rio_de_Janeiro
997,998,soja,2022-05-06,Atrasado,Uberlândia-Rio_de_Janeiro
998,999,eletrônicos,2025-02-12,A tempo,Uberlândia-Araguari
999,1000,eletrônicos,2025-01-24,Atrasado,Uberlândia-Brasília

In [64]:
entregas['Distância_km'] = entregas['Destino'].map(distancias)

In [66]:
entregas.head()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km
0,1,milho,2025-08-18,A tempo,Uberlândia-Ribeirão_Preto,300
1,2,eletrônicos,2025-06-02,A tempo,Uberlândia-Araguari,30
2,3,Disel,2024-08-20,A tempo,Uberlândia-São_Paulo,585
3,4,Gasolina,2020-12-23,A tempo,Uberlândia-Belo_Horizonte,540
4,5,Gasolina,2024-10-25,A tempo,Uberlândia-Goiânia,330

In [68]:
entregas.tail()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km
995,996,Disel,2023-01-09,A tempo,Uberlândia-Brasília,430
996,997,Queijo,2021-06-22,A tempo,Uberlândia-Rio_de_Janeiro,985
997,998,soja,2022-05-06,Atrasado,Uberlândia-Rio_de_Janeiro,985
998,999,eletrônicos,2025-02-12,A tempo,Uberlândia-Araguari,30
999,1000,eletrônicos,2025-01-24,Atrasado,Uberlândia-Brasília,430

In [70]:
consumo_medio = 3.5
preco_disel = 6.20

entregas['Custo'] = (entregas['Distância_km'] / consumo_medio) * preco_disel

In [72]:
entregas.head()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km,Custo
0,1,milho,2025-08-18,A tempo,Uberlândia-Ribeirão_Preto,300,531.428571
1,2,eletrônicos,2025-06-02,A tempo,Uberlândia-Araguari,30,53.142857
2,3,Disel,2024-08-20,A tempo,Uberlândia-São_Paulo,585,1036.285714
3,4,Gasolina,2020-12-23,A tempo,Uberlândia-Belo_Horizonte,540,956.571429
4,5,Gasolina,2024-10-25,A tempo,Uberlândia-Goiânia,330,584.571429

In [74]:
entregas.tail()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km,Custo
995,996,Disel,2023-01-09,A tempo,Uberlândia-Brasília,430,761.714286
996,997,Queijo,2021-06-22,A tempo,Uberlândia-Rio_de_Janeiro,985,1744.857143
997,998,soja,2022-05-06,Atrasado,Uberlândia-Rio_de_Janeiro,985,1744.857143
998,999,eletrônicos,2025-02-12,A tempo,Uberlândia-Araguari,30,53.142857
999,1000,eletrônicos,2025-01-24,Atrasado,Uberlândia-Brasília,430,761.714286

In [76]:
preco_por_km = 5.0
entregas["Faturamento"] = np.where(
    entregas["Status"] == "Atrasado",
    entregas["Distância_km"] * preco_por_km * 0.90,  
    entregas["Distância_km"] * preco_por_km          
)

In [78]:
entregas.head()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km,Custo,Faturamento
0,1,milho,2025-08-18,A tempo,Uberlândia-Ribeirão_Preto,300,531.428571,1500.0
1,2,eletrônicos,2025-06-02,A tempo,Uberlândia-Araguari,30,53.142857,150.0
2,3,Disel,2024-08-20,A tempo,Uberlândia-São_Paulo,585,1036.285714,2925.0
3,4,Gasolina,2020-12-23,A tempo,Uberlândia-Belo_Horizonte,540,956.571429,2700.0
4,5,Gasolina,2024-10-25,A tempo,Uberlândia-Goiânia,330,584.571429,1650.0

In [80]:
entregas.tail()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km,Custo,Faturamento
995,996,Disel,2023-01-09,A tempo,Uberlândia-Brasília,430,761.714286,2150.0
996,997,Queijo,2021-06-22,A tempo,Uberlândia-Rio_de_Janeiro,985,1744.857143,4925.0
997,998,soja,2022-05-06,Atrasado,Uberlândia-Rio_de_Janeiro,985,1744.857143,4432.5
998,999,eletrônicos,2025-02-12,A tempo,Uberlândia-Araguari,30,53.142857,150.0
999,1000,eletrônicos,2025-01-24,Atrasado,Uberlândia-Brasília,430,761.714286,1935.0

In [82]:
entregas.to_csv('C:/Users/mathe/Documents/projetos/Analise de dados/projeto-20/paranaiba-transportes/dataset/entregas.csv')

In [117]:
manutencao = pd.DataFrame({'Número_caminhão': Número_caminhao})

In [119]:
manutencao.head()

  Número_caminhão
0            1001
1            1002
2            1003
3            1004
4            1005

In [121]:
datas_manutencao = pd.date_range(start='2025-01-01', end='2026-06-30', freq='6ME')

In [123]:
manutencao['Data da última manutenção'] = np.random.choice(datas_manutencao, size=len(manutencao))

In [125]:
manutencao.head()

  Número_caminhão Data da última manutenção
0            1001                2025-01-31
1            1002                2025-01-31
2            1003                2025-07-31
3            1004                2026-01-31
4            1005                2025-01-31

In [127]:
manutencao.tail()

   Número_caminhão Data da última manutenção
95            1096                2025-01-31
96            1097                2025-07-31
97            1098                2025-01-31
98            1099                2025-01-31
99           10100                2025-01-31

In [129]:
manutencao['Data da próxima manutenção'] = manutencao['Data da última manutenção'] + pd.DateOffset(months=6)

In [131]:
manutencao.head()

  Número_caminhão Data da última manutenção Data da próxima manutenção
0            1001                2025-01-31                 2025-07-31
1            1002                2025-01-31                 2025-07-31
2            1003                2025-07-31                 2026-01-31
3            1004                2026-01-31                 2026-07-31
4            1005                2025-01-31                 2025-07-31

In [133]:
manutencao['Status de manutenção'] = np.where(
    (manutencao['Data da última manutenção'].dt.year == 2025), 
    'Atrasada',
    'Ok'
)

In [135]:
manutencao.head()

,Número_caminhão,Data da última manutenção,Data da próxima manutenção,Status de manutenção
0,1001,2025-01-31,2025-07-31,Atrasada
1,1002,2025-01-31,2025-07-31,Atrasada
2,1003,2025-07-31,2026-01-31,Atrasada
3,1004,2026-01-31,2026-07-31,Ok
4,1005,2025-01-31,2025-07-31,Atrasada

In [137]:
manutencao.tail()

,Número_caminhão,Data da última manutenção,Data da próxima manutenção,Status de manutenção
95,1096,2025-01-31,2025-07-31,Atrasada
96,1097,2025-07-31,2026-01-31,Atrasada
97,1098,2025-01-31,2025-07-31,Atrasada
98,1099,2025-01-31,2025-07-31,Atrasada
99,10100,2025-01-31,2025-07-31,Atrasada