# Criando dataset da empresa

In [2]:
import pandas as pd 
import numpy as np

Criando identificador dos caminhões.

In [4]:

ids = [f"10{str(i).zfill(2)}" for i in range(1, 101)]

veiculo = pd.DataFrame({"Número_caminhao": ids})

In [5]:
veiculo.head()

  Número_caminhao
0            1001
1            1002
2            1003
3            1004
4            1005

In [6]:
veiculo.tail()

   Número_caminhao
95            1096
96            1097
97            1098
98            1099
99           10100

Verificando o tipo de dado da coluna

In [8]:
veiculo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Número_caminhao  100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes

In [9]:
marcas = ['Scania', 'Mercedes', 'Volvo']
veiculo['marca'] = np.random.choice(marcas, size=len(veiculo))

In [10]:
veiculo.head()

  Número_caminhao     marca
0            1001     Volvo
1            1002    Scania
2            1003  Mercedes
3            1004  Mercedes
4            1005    Scania

In [11]:
veiculo.tail()

   Número_caminhao     marca
95            1096     Volvo
96            1097  Mercedes
97            1098    Scania
98            1099  Mercedes
99           10100     Volvo

In [12]:
start = pd.to_datetime("2012-01-01")
end = pd.to_datetime("2023-12-31")

n = len(veiculo)

random_dates = start + (end - start) * np.random.rand(n)

veiculo['Ano'] = random_dates

In [13]:
veiculo.head()

  Número_caminhao     marca                           Ano
0            1001     Volvo 2022-02-13 01:00:05.522827904
1            1002    Scania 2018-01-27 22:28:02.666727424
2            1003  Mercedes 2015-05-12 09:00:48.671316224
3            1004  Mercedes 2014-05-28 14:09:45.142881584
4            1005    Scania 2013-09-20 01:26:59.478378488

In [14]:
veiculo.tail()

   Número_caminhao     marca                           Ano
95            1096     Volvo 2015-04-19 03:47:08.670441264
96            1097  Mercedes 2014-11-10 01:06:21.743201616
97            1098    Scania 2022-06-12 05:24:56.321288832
98            1099  Mercedes 2012-03-12 01:40:06.966295046
99           10100     Volvo 2013-08-27 07:44:53.242218080

In [15]:
ano_de_fabricação = pd.to_datetime(veiculo['Ano']).dt.year

In [16]:
ano_de_fabricação

0     2022
1     2018
2     2015
3     2014
4     2013
      ...
95    2015
96    2014
97    2022
98    2012
99    2013
Name: Ano, Length: 100, dtype: int32

In [17]:
km = []
for ano in ano_de_fabricação:
    if ano <= 2014:
        km.append(np.random.randint(600000, 900000))
    elif ano <= 2018:
        km.append(np.random.randint(300000, 600000))
    else:
        km.append(np.random.randint(50000, 300000)) 
veiculo['Km_rodados'] = km

In [18]:
veiculo.head()

  Número_caminhao     marca                           Ano  Km_rodados
0            1001     Volvo 2022-02-13 01:00:05.522827904      110496
1            1002    Scania 2018-01-27 22:28:02.666727424      346295
2            1003  Mercedes 2015-05-12 09:00:48.671316224      442854
3            1004  Mercedes 2014-05-28 14:09:45.142881584      715342
4            1005    Scania 2013-09-20 01:26:59.478378488      867200

In [19]:
tipo = ['rígido', 'articulado']

veiculo['tipo'] = np.random.choice(tipo, size=len(veiculo))

In [20]:
veiculo.head()

,Número_caminhao,marca,Ano,Km_rodados,tipo
0,1001,Volvo,2022-02-13 01:00:05.522827904,110496,rígido
1,1002,Scania,2018-01-27 22:28:02.666727424,346295,articulado
2,1003,Mercedes,2015-05-12 09:00:48.671316224,442854,rígido
3,1004,Mercedes,2014-05-28 14:09:45.142881584,715342,articulado
4,1005,Scania,2013-09-20 01:26:59.478378488,867200,articulado

In [21]:
veiculo.to_csv("C:/Users/mathe/Documents/projetos/Analise de dados/projeto-20/paranaiba-transportes/dataset/veiculos.csv", index=False)

In [22]:
Número_caminhao = veiculo['Número_caminhao']

In [23]:
rotas_lista = [
    'Uberlândia-São_Paulo',
    'Uberlândia-Belo_Horizonte',
    'Uberlândia-Brasília',
    'Uberlândia-Goiânia',
    'Uberlândia-Rio_de_Janeiro',
    'Uberlândia-Uberaba',
    'Uberlândia-Araguari',
    'Uberlândia-Catalão',
    'Uberlândia-Ribeirão_Preto'
]

In [24]:
rotas = pd.DataFrame({'Número_Caminhão': Número_caminhao})

In [25]:
rotas.head()

  Número_Caminhão
0            1001
1            1002
2            1003
3            1004
4            1005

In [26]:
rotas['rotas'] = np.random.choice(rotas_lista, size=len(rotas))

In [27]:
rotas.head()

  Número_Caminhão                      rotas
0            1001        Uberlândia-Brasília
1            1002         Uberlândia-Catalão
2            1003  Uberlândia-Ribeirão_Preto
3            1004         Uberlândia-Catalão
4            1005        Uberlândia-Araguari

In [28]:
rotas.tail()

   Número_Caminhão                      rotas
95            1096  Uberlândia-Ribeirão_Preto
96            1097        Uberlândia-Araguari
97            1098  Uberlândia-Rio_de_Janeiro
98            1099        Uberlândia-Brasília
99           10100  Uberlândia-Ribeirão_Preto

In [29]:
distancias = {   
    'Uberlândia-São_Paulo':585,
    'Uberlândia-Belo_Horizonte':540,
    'Uberlândia-Brasília':430,
    'Uberlândia-Goiânia':330,
    'Uberlândia-Rio_de_Janeiro':985,
    'Uberlândia-Uberaba':110,
    'Uberlândia-Araguari':30,
    'Uberlândia-Catalão':190,
    'Uberlândia-Ribeirão_Preto': 300
}

In [31]:
rotas['Distância_km'] = rotas['rotas'].map(distancias)

In [33]:
rotas.head()

  Número_Caminhão                      rotas  Distância_km
0            1001        Uberlândia-Brasília           430
1            1002         Uberlândia-Catalão           190
2            1003  Uberlândia-Ribeirão_Preto           300
3            1004         Uberlândia-Catalão           190
4            1005        Uberlândia-Araguari            30

In [35]:
rotas.tail()

   Número_Caminhão                      rotas  Distância_km
95            1096  Uberlândia-Ribeirão_Preto           300
96            1097        Uberlândia-Araguari            30
97            1098  Uberlândia-Rio_de_Janeiro           985
98            1099        Uberlândia-Brasília           430
99           10100  Uberlândia-Ribeirão_Preto           300

In [37]:
velocidade_media = 80
rotas['Tempo_estimado_horas'] = rotas['Distância_km'] / velocidade_media

In [39]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas
0,1001,Uberlândia-Brasília,430,5.375
1,1002,Uberlândia-Catalão,190,2.375
2,1003,Uberlândia-Ribeirão_Preto,300,3.750
3,1004,Uberlândia-Catalão,190,2.375
4,1005,Uberlândia-Araguari,30,0.375

In [41]:
rotas.tail()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas
95,1096,Uberlândia-Ribeirão_Preto,300,3.7500
96,1097,Uberlândia-Araguari,30,0.3750
97,1098,Uberlândia-Rio_de_Janeiro,985,12.3125
98,1099,Uberlândia-Brasília,430,5.3750
99,10100,Uberlândia-Ribeirão_Preto,300,3.7500

In [43]:
tipo_de_carga = ['agrícola', 'industrial', 'consumo']

In [47]:
rotas['Tipo_De_Carga'] = np.random.choice(tipo_de_carga, size=len(rotas))

In [49]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas,Tipo_De_Carga
0,1001,Uberlândia-Brasília,430,5.375,consumo
1,1002,Uberlândia-Catalão,190,2.375,consumo
2,1003,Uberlândia-Ribeirão_Preto,300,3.750,agrícola
3,1004,Uberlândia-Catalão,190,2.375,industrial
4,1005,Uberlândia-Araguari,30,0.375,agrícola

In [51]:
frequencia = ['díaria', 'semanal', 'mensal']

In [56]:
rotas['Frequência'] = np.random.choice(frequencia, size=len(rotas))

In [58]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas,Tipo_De_Carga,Frequência
0,1001,Uberlândia-Brasília,430,5.375,consumo,díaria
1,1002,Uberlândia-Catalão,190,2.375,consumo,semanal
2,1003,Uberlândia-Ribeirão_Preto,300,3.750,agrícola,semanal
3,1004,Uberlândia-Catalão,190,2.375,industrial,díaria
4,1005,Uberlândia-Araguari,30,0.375,agrícola,semanal

In [60]:
rotas.to_csv('C:/Users/mathe/Documents/projetos/Analise de dados/projeto-20/paranaiba-transportes/dataset/rotas.csv')