# Criando dataset da empresa

In [101]:
import pandas as pd 
import numpy as np
import datetime as dt

Criando identificador dos caminhões.

In [4]:

ids = [f"10{str(i).zfill(2)}" for i in range(1, 101)]

veiculo = pd.DataFrame({"Número_caminhao": ids})

In [5]:
veiculo.head()

  Número_caminhao
0            1001
1            1002
2            1003
3            1004
4            1005

In [6]:
veiculo.tail()

   Número_caminhao
95            1096
96            1097
97            1098
98            1099
99           10100

Verificando o tipo de dado da coluna

In [8]:
veiculo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Número_caminhao  100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes

In [9]:
marcas = ['Scania', 'Mercedes', 'Volvo']
veiculo['marca'] = np.random.choice(marcas, size=len(veiculo))

In [10]:
veiculo.head()

  Número_caminhao     marca
0            1001     Volvo
1            1002  Mercedes
2            1003  Mercedes
3            1004    Scania
4            1005  Mercedes

In [11]:
veiculo.tail()

   Número_caminhao     marca
95            1096    Scania
96            1097    Scania
97            1098     Volvo
98            1099     Volvo
99           10100  Mercedes

In [12]:
start = pd.to_datetime("2012-01-01")
end = pd.to_datetime("2023-12-31")

n = len(veiculo)

random_dates = start + (end - start) * np.random.rand(n)

veiculo['Ano'] = random_dates

In [13]:
veiculo.head()

  Número_caminhao     marca                           Ano
0            1001     Volvo 2017-06-08 13:09:58.988066880
1            1002  Mercedes 2017-10-18 22:10:29.952210656
2            1003  Mercedes 2023-12-16 04:17:56.323406976
3            1004    Scania 2022-01-16 15:32:48.089578880
4            1005  Mercedes 2016-09-19 07:23:59.795257440

In [14]:
veiculo.tail()

   Número_caminhao     marca                           Ano
95            1096    Scania 2013-01-01 17:12:43.849762008
96            1097    Scania 2017-10-12 22:11:41.242848608
97            1098     Volvo 2015-01-08 21:04:03.837775744
98            1099     Volvo 2017-02-26 18:11:25.322766144
99           10100  Mercedes 2020-11-04 13:14:31.436195456

In [15]:
ano_de_fabricação = pd.to_datetime(veiculo['Ano']).dt.year

In [16]:
ano_de_fabricação

0     2017
1     2017
2     2023
3     2022
4     2016
      ...
95    2013
96    2017
97    2015
98    2017
99    2020
Name: Ano, Length: 100, dtype: int32

In [17]:
km = []
for ano in ano_de_fabricação:
    if ano <= 2014:
        km.append(np.random.randint(600000, 900000))
    elif ano <= 2018:
        km.append(np.random.randint(300000, 600000))
    else:
        km.append(np.random.randint(50000, 300000)) 
veiculo['Km_rodados'] = km

In [18]:
veiculo.head()

  Número_caminhao     marca                           Ano  Km_rodados
0            1001     Volvo 2017-06-08 13:09:58.988066880      320155
1            1002  Mercedes 2017-10-18 22:10:29.952210656      576767
2            1003  Mercedes 2023-12-16 04:17:56.323406976      193138
3            1004    Scania 2022-01-16 15:32:48.089578880      263850
4            1005  Mercedes 2016-09-19 07:23:59.795257440      539281

In [19]:
tipo = ['rígido', 'articulado']

veiculo['tipo'] = np.random.choice(tipo, size=len(veiculo))

In [20]:
veiculo.head()

,Número_caminhao,marca,Ano,Km_rodados,tipo
0,1001,Volvo,2017-06-08 13:09:58.988066880,320155,articulado
1,1002,Mercedes,2017-10-18 22:10:29.952210656,576767,rígido
2,1003,Mercedes,2023-12-16 04:17:56.323406976,193138,rígido
3,1004,Scania,2022-01-16 15:32:48.089578880,263850,articulado
4,1005,Mercedes,2016-09-19 07:23:59.795257440,539281,rígido

In [21]:
veiculo.to_csv("C:/Users/mathe/Documents/projetos/Analise de dados/projeto-20/paranaiba-transportes/dataset/veiculos.csv", index=False)

In [22]:
Número_caminhao = veiculo['Número_caminhao']

In [23]:
rotas_lista = [
    'Uberlândia-São_Paulo',
    'Uberlândia-Belo_Horizonte',
    'Uberlândia-Brasília',
    'Uberlândia-Goiânia',
    'Uberlândia-Rio_de_Janeiro',
    'Uberlândia-Uberaba',
    'Uberlândia-Araguari',
    'Uberlândia-Catalão',
    'Uberlândia-Ribeirão_Preto'
]

In [24]:
rotas = pd.DataFrame({'Número_Caminhão': Número_caminhao})

In [25]:
rotas.head()

  Número_Caminhão
0            1001
1            1002
2            1003
3            1004
4            1005

In [26]:
rotas['rotas'] = np.random.choice(rotas_lista, size=len(rotas))

In [27]:
rotas.head()

  Número_Caminhão                      rotas
0            1001  Uberlândia-Rio_de_Janeiro
1            1002        Uberlândia-Araguari
2            1003  Uberlândia-Belo_Horizonte
3            1004         Uberlândia-Uberaba
4            1005         Uberlândia-Goiânia

In [28]:
rotas.tail()

   Número_Caminhão                      rotas
95            1096         Uberlândia-Catalão
96            1097  Uberlândia-Belo_Horizonte
97            1098  Uberlândia-Rio_de_Janeiro
98            1099         Uberlândia-Uberaba
99           10100        Uberlândia-Araguari

In [29]:
distancias = {   
    'Uberlândia-São_Paulo':585,
    'Uberlândia-Belo_Horizonte':540,
    'Uberlândia-Brasília':430,
    'Uberlândia-Goiânia':330,
    'Uberlândia-Rio_de_Janeiro':985,
    'Uberlândia-Uberaba':110,
    'Uberlândia-Araguari':30,
    'Uberlândia-Catalão':190,
    'Uberlândia-Ribeirão_Preto': 300
}

In [30]:
rotas['Distância_km'] = rotas['rotas'].map(distancias)

In [31]:
rotas.head()

  Número_Caminhão                      rotas  Distância_km
0            1001  Uberlândia-Rio_de_Janeiro           985
1            1002        Uberlândia-Araguari            30
2            1003  Uberlândia-Belo_Horizonte           540
3            1004         Uberlândia-Uberaba           110
4            1005         Uberlândia-Goiânia           330

In [32]:
rotas.tail()

   Número_Caminhão                      rotas  Distância_km
95            1096         Uberlândia-Catalão           190
96            1097  Uberlândia-Belo_Horizonte           540
97            1098  Uberlândia-Rio_de_Janeiro           985
98            1099         Uberlândia-Uberaba           110
99           10100        Uberlândia-Araguari            30

In [33]:
velocidade_media = 80
rotas['Tempo_estimado_horas'] = rotas['Distância_km'] / velocidade_media

In [34]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas
0,1001,Uberlândia-Rio_de_Janeiro,985,12.3125
1,1002,Uberlândia-Araguari,30,0.3750
2,1003,Uberlândia-Belo_Horizonte,540,6.7500
3,1004,Uberlândia-Uberaba,110,1.3750
4,1005,Uberlândia-Goiânia,330,4.1250

In [35]:
rotas.tail()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas
95,1096,Uberlândia-Catalão,190,2.3750
96,1097,Uberlândia-Belo_Horizonte,540,6.7500
97,1098,Uberlândia-Rio_de_Janeiro,985,12.3125
98,1099,Uberlândia-Uberaba,110,1.3750
99,10100,Uberlândia-Araguari,30,0.3750

In [36]:
tipo_de_carga = ['agrícola', 'industrial', 'consumo']

In [37]:
rotas['Tipo_De_Carga'] = np.random.choice(tipo_de_carga, size=len(rotas))

In [38]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas,Tipo_De_Carga
0,1001,Uberlândia-Rio_de_Janeiro,985,12.3125,industrial
1,1002,Uberlândia-Araguari,30,0.3750,industrial
2,1003,Uberlândia-Belo_Horizonte,540,6.7500,consumo
3,1004,Uberlândia-Uberaba,110,1.3750,consumo
4,1005,Uberlândia-Goiânia,330,4.1250,industrial

In [39]:
frequencia = ['díaria', 'semanal', 'mensal']

In [40]:
rotas['Frequência'] = np.random.choice(frequencia, size=len(rotas))

In [41]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas,Tipo_De_Carga,Frequência
0,1001,Uberlândia-Rio_de_Janeiro,985,12.3125,industrial,mensal
1,1002,Uberlândia-Araguari,30,0.3750,industrial,díaria
2,1003,Uberlândia-Belo_Horizonte,540,6.7500,consumo,díaria
3,1004,Uberlândia-Uberaba,110,1.3750,consumo,semanal
4,1005,Uberlândia-Goiânia,330,4.1250,industrial,semanal

In [42]:
rotas.to_csv('C:/Users/mathe/Documents/projetos/Analise de dados/projeto-20/paranaiba-transportes/dataset/rotas.csv')

In [88]:
produtos_list = [
    'glp', 
    'Disel', 
    'Gasolina', 
    'soja',
    'milho',
    'café',
    'eletrônicos',
    'Carnes',
    'Queijo'
]

In [83]:
n_entregas = 1000

In [92]:
entregas = pd.DataFrame({"Produtos": np.random.choice(produtos_list, size=n_entregas)})

In [94]:
entregas['id_entrega'] = range(1, n_entregas + 1)

cols = ['id_entrega'] + [col for col in entregas.columns if col != 'id_entrega']
entregas = entregas[cols]

In [96]:
entregas.head()

   id_entrega Produtos
0           1    Disel
1           2    Disel
2           3    Disel
3           4   Queijo
4           5   Queijo

In [98]:
entregas.tail()

     id_entrega     Produtos
995         996  eletrônicos
996         997        Disel
997         998         café
998         999       Carnes
999        1000         café

In [105]:
start = pd.to_datetime('2020-01-01')
end = pd.to_datetime('2025-12-31')

random_entregas_dates = start + (end - start) * np.random.rand(n_entregas) 

entregas['Data_da_entrega'] = pd.to_datetime(random_entregas_dates).normalize()

In [107]:
entregas.head()

   id_entrega Produtos Data_da_entrega
0           1    Disel      2025-01-25
1           2    Disel      2024-07-04
2           3    Disel      2024-07-09
3           4   Queijo      2023-02-15
4           5   Queijo      2023-11-25

In [109]:
entregas.tail()

     id_entrega     Produtos Data_da_entrega
995         996  eletrônicos      2024-03-31
996         997        Disel      2025-01-08
997         998         café      2024-04-21
998         999       Carnes      2021-07-19
999        1000         café      2024-05-29