# Criando dataset da empresa

In [2]:
import pandas as pd 
import numpy as np
import datetime as dt

Criando identificador dos caminhões.

In [4]:

ids = [f"10{str(i).zfill(2)}" for i in range(1, 101)]

veiculo = pd.DataFrame({"Número_caminhao": ids})

In [5]:
veiculo.head()

  Número_caminhao
0            1001
1            1002
2            1003
3            1004
4            1005

In [6]:
veiculo.tail()

   Número_caminhao
95            1096
96            1097
97            1098
98            1099
99           10100

Verificando o tipo de dado da coluna

In [8]:
veiculo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Número_caminhao  100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes

In [9]:
marcas = ['Scania', 'Mercedes', 'Volvo']
veiculo['marca'] = np.random.choice(marcas, size=len(veiculo))

In [10]:
veiculo.head()

  Número_caminhao     marca
0            1001     Volvo
1            1002    Scania
2            1003  Mercedes
3            1004    Scania
4            1005     Volvo

In [11]:
veiculo.tail()

   Número_caminhao     marca
95            1096    Scania
96            1097     Volvo
97            1098  Mercedes
98            1099    Scania
99           10100    Scania

In [12]:
start = pd.to_datetime("2012-01-01")
end = pd.to_datetime("2023-12-31")

n = len(veiculo)

random_dates = start + (end - start) * np.random.rand(n)

veiculo['Ano'] = random_dates

In [13]:
veiculo.head()

  Número_caminhao     marca                           Ano
0            1001     Volvo 2017-10-13 03:36:27.071216672
1            1002    Scania 2022-02-24 11:02:04.457344768
2            1003  Mercedes 2017-03-06 16:10:15.428980384
3            1004    Scania 2016-09-01 02:07:12.855423456
4            1005     Volvo 2022-05-08 01:23:09.859292992

In [14]:
veiculo.tail()

   Número_caminhao     marca                           Ano
95            1096    Scania 2017-05-13 15:50:57.337075360
96            1097     Volvo 2016-11-15 11:28:21.191469120
97            1098  Mercedes 2021-12-01 16:08:11.071218368
98            1099    Scania 2020-01-31 15:54:25.919193536
99           10100    Scania 2023-01-17 12:13:08.137265664

In [15]:
ano_de_fabricação = pd.to_datetime(veiculo['Ano']).dt.year

In [16]:
ano_de_fabricação

0     2017
1     2022
2     2017
3     2016
4     2022
      ...
95    2017
96    2016
97    2021
98    2020
99    2023
Name: Ano, Length: 100, dtype: int32

In [17]:
km = []
for ano in ano_de_fabricação:
    if ano <= 2014:
        km.append(np.random.randint(600000, 900000))
    elif ano <= 2018:
        km.append(np.random.randint(300000, 600000))
    else:
        km.append(np.random.randint(50000, 300000)) 
veiculo['Km_rodados'] = km

In [18]:
veiculo.head()

  Número_caminhao     marca                           Ano  Km_rodados
0            1001     Volvo 2017-10-13 03:36:27.071216672      471061
1            1002    Scania 2022-02-24 11:02:04.457344768       87564
2            1003  Mercedes 2017-03-06 16:10:15.428980384      315005
3            1004    Scania 2016-09-01 02:07:12.855423456      357637
4            1005     Volvo 2022-05-08 01:23:09.859292992      107084

In [19]:
tipo = ['rígido', 'articulado']

veiculo['tipo'] = np.random.choice(tipo, size=len(veiculo))

In [20]:
veiculo.head()

,Número_caminhao,marca,Ano,Km_rodados,tipo
0,1001,Volvo,2017-10-13 03:36:27.071216672,471061,rígido
1,1002,Scania,2022-02-24 11:02:04.457344768,87564,articulado
2,1003,Mercedes,2017-03-06 16:10:15.428980384,315005,rígido
3,1004,Scania,2016-09-01 02:07:12.855423456,357637,rígido
4,1005,Volvo,2022-05-08 01:23:09.859292992,107084,articulado

In [21]:
veiculo.to_csv("C:/Users/mathe/Documents/projetos/Analise de dados/projeto-20/paranaiba-transportes/dataset/veiculos.csv", index=False)

In [22]:
Número_caminhao = veiculo['Número_caminhao']

In [23]:
rotas_lista = [
    'Uberlândia-São_Paulo',
    'Uberlândia-Belo_Horizonte',
    'Uberlândia-Brasília',
    'Uberlândia-Goiânia',
    'Uberlândia-Rio_de_Janeiro',
    'Uberlândia-Uberaba',
    'Uberlândia-Araguari',
    'Uberlândia-Catalão',
    'Uberlândia-Ribeirão_Preto'
]

In [24]:
rotas = pd.DataFrame({'Número_Caminhão': Número_caminhao})

In [25]:
rotas.head()

  Número_Caminhão
0            1001
1            1002
2            1003
3            1004
4            1005

In [26]:
rotas['rotas'] = np.random.choice(rotas_lista, size=len(rotas))

In [27]:
rotas.head()

  Número_Caminhão                      rotas
0            1001  Uberlândia-Belo_Horizonte
1            1002         Uberlândia-Uberaba
2            1003        Uberlândia-Araguari
3            1004         Uberlândia-Uberaba
4            1005         Uberlândia-Goiânia

In [28]:
rotas.tail()

   Número_Caminhão                 rotas
95            1096    Uberlândia-Goiânia
96            1097   Uberlândia-Araguari
97            1098  Uberlândia-São_Paulo
98            1099   Uberlândia-Araguari
99           10100  Uberlândia-São_Paulo

In [29]:
distancias = {   
    'Uberlândia-São_Paulo':585,
    'Uberlândia-Belo_Horizonte':540,
    'Uberlândia-Brasília':430,
    'Uberlândia-Goiânia':330,
    'Uberlândia-Rio_de_Janeiro':985,
    'Uberlândia-Uberaba':110,
    'Uberlândia-Araguari':30,
    'Uberlândia-Catalão':190,
    'Uberlândia-Ribeirão_Preto': 300
}

In [30]:
rotas['Distância_km'] = rotas['rotas'].map(distancias)

In [31]:
rotas.head()

  Número_Caminhão                      rotas  Distância_km
0            1001  Uberlândia-Belo_Horizonte           540
1            1002         Uberlândia-Uberaba           110
2            1003        Uberlândia-Araguari            30
3            1004         Uberlândia-Uberaba           110
4            1005         Uberlândia-Goiânia           330

In [32]:
rotas.tail()

   Número_Caminhão                 rotas  Distância_km
95            1096    Uberlândia-Goiânia           330
96            1097   Uberlândia-Araguari            30
97            1098  Uberlândia-São_Paulo           585
98            1099   Uberlândia-Araguari            30
99           10100  Uberlândia-São_Paulo           585

In [33]:
velocidade_media = 80
rotas['Tempo_estimado_horas'] = rotas['Distância_km'] / velocidade_media

In [34]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas
0,1001,Uberlândia-Belo_Horizonte,540,6.750
1,1002,Uberlândia-Uberaba,110,1.375
2,1003,Uberlândia-Araguari,30,0.375
3,1004,Uberlândia-Uberaba,110,1.375
4,1005,Uberlândia-Goiânia,330,4.125

In [35]:
rotas.tail()

   Número_Caminhão                 rotas  Distância_km  Tempo_estimado_horas
95            1096    Uberlândia-Goiânia           330                4.1250
96            1097   Uberlândia-Araguari            30                0.3750
97            1098  Uberlândia-São_Paulo           585                7.3125
98            1099   Uberlândia-Araguari            30                0.3750
99           10100  Uberlândia-São_Paulo           585                7.3125

In [36]:
tipo_de_carga = ['agrícola', 'industrial', 'consumo']

In [37]:
rotas['Tipo_De_Carga'] = np.random.choice(tipo_de_carga, size=len(rotas))

In [38]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas,Tipo_De_Carga
0,1001,Uberlândia-Belo_Horizonte,540,6.750,agrícola
1,1002,Uberlândia-Uberaba,110,1.375,agrícola
2,1003,Uberlândia-Araguari,30,0.375,consumo
3,1004,Uberlândia-Uberaba,110,1.375,consumo
4,1005,Uberlândia-Goiânia,330,4.125,industrial

In [39]:
frequencia = ['díaria', 'semanal', 'mensal']

In [40]:
rotas['Frequência'] = np.random.choice(frequencia, size=len(rotas))

In [41]:
rotas.head()

,Número_Caminhão,rotas,Distância_km,Tempo_estimado_horas,Tipo_De_Carga,Frequência
0,1001,Uberlândia-Belo_Horizonte,540,6.750,agrícola,díaria
1,1002,Uberlândia-Uberaba,110,1.375,agrícola,mensal
2,1003,Uberlândia-Araguari,30,0.375,consumo,díaria
3,1004,Uberlândia-Uberaba,110,1.375,consumo,mensal
4,1005,Uberlândia-Goiânia,330,4.125,industrial,mensal

In [42]:
rotas.to_csv('C:/Users/mathe/Documents/projetos/Analise de dados/projeto-20/paranaiba-transportes/dataset/rotas.csv')

In [43]:
produtos_list = [
    'glp', 
    'Disel', 
    'Gasolina', 
    'soja',
    'milho',
    'café',
    'eletrônicos',
    'Carnes',
    'Queijo'
]

In [44]:
n_entregas = 1000

In [45]:
entregas = pd.DataFrame({"Produtos": np.random.choice(produtos_list, size=n_entregas)})

In [46]:
entregas['id_entrega'] = range(1, n_entregas + 1)

cols = ['id_entrega'] + [col for col in entregas.columns if col != 'id_entrega']
entregas = entregas[cols]

In [47]:
entregas.head()

   id_entrega  Produtos
0           1      café
1           2  Gasolina
2           3  Gasolina
3           4     Disel
4           5       glp

In [48]:
entregas.tail()

     id_entrega     Produtos
995         996     Gasolina
996         997  eletrônicos
997         998       Carnes
998         999        milho
999        1000       Carnes

In [49]:
start = pd.to_datetime('2020-01-01')
end = pd.to_datetime('2025-12-31')

random_entregas_dates = start + (end - start) * np.random.rand(n_entregas) 

entregas['Data_da_entrega'] = pd.to_datetime(random_entregas_dates).normalize()

In [50]:
entregas.head()

   id_entrega  Produtos Data_da_entrega
0           1      café      2020-01-18
1           2  Gasolina      2021-07-05
2           3  Gasolina      2024-11-21
3           4     Disel      2022-06-01
4           5       glp      2020-08-11

In [51]:
entregas.tail()

     id_entrega     Produtos Data_da_entrega
995         996     Gasolina      2020-08-14
996         997  eletrônicos      2021-05-22
997         998       Carnes      2022-06-30
998         999        milho      2021-09-21
999        1000       Carnes      2024-04-09

In [104]:
status_lista = ['A tempo', 'Atrasado']
entregas['Status'] = np.random.choice(status_lista, size = len(entregas))

In [106]:
entregas.head()

   id_entrega  Produtos Data_da_entrega    Status
0           1      café      2020-01-18   A tempo
1           2  Gasolina      2021-07-05   A tempo
2           3  Gasolina      2024-11-21  Atrasado
3           4     Disel      2022-06-01   A tempo
4           5       glp      2020-08-11   A tempo

In [108]:
entregas.tail()

     id_entrega     Produtos Data_da_entrega    Status
995         996     Gasolina      2020-08-14  Atrasado
996         997  eletrônicos      2021-05-22  Atrasado
997         998       Carnes      2022-06-30   A tempo
998         999        milho      2021-09-21  Atrasado
999        1000       Carnes      2024-04-09  Atrasado

In [124]:
entregas.head()

   id_entrega  Produtos Data_da_entrega    Status        custo        Custo
0           1      café      2020-01-18   A tempo  1078.457143  1078.457143
1           2  Gasolina      2021-07-05   A tempo   219.685714   219.685714
2           3  Gasolina      2024-11-21  Atrasado    59.914286    59.914286
3           4     Disel      2022-06-01   A tempo   219.685714   219.685714
4           5       glp      2020-08-11   A tempo   659.057143   659.057143

In [128]:
entregas.drop(columns=['custo', 'Custo'])

     id_entrega     Produtos Data_da_entrega    Status
0             1         café      2020-01-18   A tempo
1             2     Gasolina      2021-07-05   A tempo
2             3     Gasolina      2024-11-21  Atrasado
3             4        Disel      2022-06-01   A tempo
4             5          glp      2020-08-11   A tempo
..          ...          ...             ...       ...
995         996     Gasolina      2020-08-14  Atrasado
996         997  eletrônicos      2021-05-22  Atrasado
997         998       Carnes      2022-06-30   A tempo
998         999        milho      2021-09-21  Atrasado
999        1000       Carnes      2024-04-09  Atrasado

[1000 rows x 4 columns]

In [132]:
entregas['Destino'] = np.random.choice(rotas_lista, size = len(entregas))

In [134]:
entregas.head()

,id_entrega,Produtos,Data_da_entrega,Status,custo,Custo,Destino
0,1,café,2020-01-18,A tempo,1078.457143,1078.457143,Uberlândia-Catalão
1,2,Gasolina,2021-07-05,A tempo,219.685714,219.685714,Uberlândia-Araguari
2,3,Gasolina,2024-11-21,Atrasado,59.914286,59.914286,Uberlândia-Ribeirão_Preto
3,4,Disel,2022-06-01,A tempo,219.685714,219.685714,Uberlândia-Belo_Horizonte
4,5,glp,2020-08-11,A tempo,659.057143,659.057143,Uberlândia-Araguari

In [136]:
entregas.tail()

,id_entrega,Produtos,Data_da_entrega,Status,custo,Custo,Destino
995,996,Gasolina,2020-08-14,Atrasado,NaN,NaN,Uberlândia-Araguari
996,997,eletrônicos,2021-05-22,Atrasado,NaN,NaN,Uberlândia-Catalão
997,998,Carnes,2022-06-30,A tempo,NaN,NaN,Uberlândia-Uberaba
998,999,milho,2021-09-21,Atrasado,NaN,NaN,Uberlândia-Ribeirão_Preto
999,1000,Carnes,2024-04-09,Atrasado,NaN,NaN,Uberlândia-Goiânia

In [151]:
entregas = entregas.drop(columns=['custo', 'Custo'])

In [153]:
entregas['Distância_km'] = entregas['Destino'].map(distancias)

In [155]:
entregas.head()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km
0,1,café,2020-01-18,A tempo,Uberlândia-Catalão,190
1,2,Gasolina,2021-07-05,A tempo,Uberlândia-Araguari,30
2,3,Gasolina,2024-11-21,Atrasado,Uberlândia-Ribeirão_Preto,300
3,4,Disel,2022-06-01,A tempo,Uberlândia-Belo_Horizonte,540
4,5,glp,2020-08-11,A tempo,Uberlândia-Araguari,30

In [157]:
entregas.tail()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km
995,996,Gasolina,2020-08-14,Atrasado,Uberlândia-Araguari,30
996,997,eletrônicos,2021-05-22,Atrasado,Uberlândia-Catalão,190
997,998,Carnes,2022-06-30,A tempo,Uberlândia-Uberaba,110
998,999,milho,2021-09-21,Atrasado,Uberlândia-Ribeirão_Preto,300
999,1000,Carnes,2024-04-09,Atrasado,Uberlândia-Goiânia,330

In [159]:
consumo_medio = 3.5
preco_disel = 6.20

entregas['Custo'] = (entregas['Distância_km'] / consumo_medio) * preco_disel

In [161]:
entregas.head()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km,Custo
0,1,café,2020-01-18,A tempo,Uberlândia-Catalão,190,336.571429
1,2,Gasolina,2021-07-05,A tempo,Uberlândia-Araguari,30,53.142857
2,3,Gasolina,2024-11-21,Atrasado,Uberlândia-Ribeirão_Preto,300,531.428571
3,4,Disel,2022-06-01,A tempo,Uberlândia-Belo_Horizonte,540,956.571429
4,5,glp,2020-08-11,A tempo,Uberlândia-Araguari,30,53.142857

In [163]:
entregas.tail()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km,Custo
995,996,Gasolina,2020-08-14,Atrasado,Uberlândia-Araguari,30,53.142857
996,997,eletrônicos,2021-05-22,Atrasado,Uberlândia-Catalão,190,336.571429
997,998,Carnes,2022-06-30,A tempo,Uberlândia-Uberaba,110,194.857143
998,999,milho,2021-09-21,Atrasado,Uberlândia-Ribeirão_Preto,300,531.428571
999,1000,Carnes,2024-04-09,Atrasado,Uberlândia-Goiânia,330,584.571429

In [169]:
preco_por_km = 5.0
entregas["Faturamento"] = np.where(
    entregas["Status"] == "Atrasado",
    entregas["Distância_km"] * preco_por_km * 0.90,  
    entregas["Distância_km"] * preco_por_km          
)

In [171]:
entregas.head()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km,Custo,Faturamento
0,1,café,2020-01-18,A tempo,Uberlândia-Catalão,190,336.571429,950.0
1,2,Gasolina,2021-07-05,A tempo,Uberlândia-Araguari,30,53.142857,150.0
2,3,Gasolina,2024-11-21,Atrasado,Uberlândia-Ribeirão_Preto,300,531.428571,1350.0
3,4,Disel,2022-06-01,A tempo,Uberlândia-Belo_Horizonte,540,956.571429,2700.0
4,5,glp,2020-08-11,A tempo,Uberlândia-Araguari,30,53.142857,150.0

In [173]:
entregas.tail()

,id_entrega,Produtos,Data_da_entrega,Status,Destino,Distância_km,Custo,Faturamento
995,996,Gasolina,2020-08-14,Atrasado,Uberlândia-Araguari,30,53.142857,135.0
996,997,eletrônicos,2021-05-22,Atrasado,Uberlândia-Catalão,190,336.571429,855.0
997,998,Carnes,2022-06-30,A tempo,Uberlândia-Uberaba,110,194.857143,550.0
998,999,milho,2021-09-21,Atrasado,Uberlândia-Ribeirão_Preto,300,531.428571,1350.0
999,1000,Carnes,2024-04-09,Atrasado,Uberlândia-Goiânia,330,584.571429,1485.0