# Criando dataset da empresa

In [2]:
import pandas as pd 
import numpy as np

Criando identificador dos caminhões.

In [4]:

ids = [f"10{str(i).zfill(2)}" for i in range(1, 101)]

veiculo = pd.DataFrame({"Número_caminhao": ids})

In [5]:
veiculo.head()

  Número_caminhao
0            1001
1            1002
2            1003
3            1004
4            1005

In [6]:
veiculo.tail()

   Número_caminhao
95            1096
96            1097
97            1098
98            1099
99           10100

Verificando o tipo de dado da coluna

In [8]:
veiculo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Número_caminhao  100 non-null    object
dtypes: object(1)
memory usage: 932.0+ bytes

In [9]:
marcas = ['Scania', 'Mercedes', 'Volvo']
veiculo['marca'] = np.random.choice(marcas, size=len(veiculo))

In [16]:
veiculo.head()

  Número_caminhao     marca
0            1001     Volvo
1            1002    Scania
2            1003     Volvo
3            1004  Mercedes
4            1005    Scania

In [18]:
veiculo.tail()

   Número_caminhao     marca
95            1096  Mercedes
96            1097    Scania
97            1098    Scania
98            1099    Scania
99           10100     Volvo

In [28]:
start = pd.to_datetime("2012-01-01")
end = pd.to_datetime("2023-12-31")

n = len(veiculo)

random_dates = start + (end - start) * np.random.rand(n)

veiculo['Ano'] = random_dates

In [34]:
veiculo.head()

  Número_caminhao     marca                           Ano
0            1001     Volvo 2020-09-23 20:49:31.656271232
1            1002    Scania 2015-02-16 04:10:29.536728720
2            1003     Volvo 2018-08-04 19:53:19.430278048
3            1004  Mercedes 2020-03-30 00:56:07.355786368
4            1005    Scania 2018-11-11 01:15:12.014872544

In [36]:
veiculo.tail()

   Número_caminhao     marca                           Ano
95            1096  Mercedes 2014-04-20 17:06:12.009000464
96            1097    Scania 2012-10-21 08:53:15.769804208
97            1098    Scania 2020-01-22 11:03:03.462247392
98            1099    Scania 2014-03-22 03:38:33.505948752
99           10100     Volvo 2016-12-21 21:00:42.181323104

In [30]:
ano_de_fabricação = pd.to_datetime(veiculo['Ano']).dt.year

In [32]:
ano_de_fabricação

0     2020
1     2015
2     2018
3     2020
4     2018
      ...
95    2014
96    2012
97    2020
98    2014
99    2016
Name: Ano, Length: 100, dtype: int32

In [42]:
km = []
for ano in ano_de_fabricação:
    if ano <= 2014:
        km.append(np.random.randint(600000, 900000))
    elif ano <= 2018:
        km.append(np.random.randint(300000, 600000))
    else:
        km.append(np.random.randint(50000, 300000)) 
veiculo['Km_rodados'] = km

In [44]:
veiculo.head()

  Número_caminhao     marca                           Ano  Km_rodados
0            1001     Volvo 2020-09-23 20:49:31.656271232      244860
1            1002    Scania 2015-02-16 04:10:29.536728720      378400
2            1003     Volvo 2018-08-04 19:53:19.430278048      401246
3            1004  Mercedes 2020-03-30 00:56:07.355786368      174410
4            1005    Scania 2018-11-11 01:15:12.014872544      353975

In [46]:
tipo = ['rígido', 'articulado']

veiculo['tipo'] = np.random.choice(tipo, size=len(veiculo))

In [48]:
veiculo.head()

,Número_caminhao,marca,Ano,Km_rodados,tipo
0,1001,Volvo,2020-09-23 20:49:31.656271232,244860,articulado
1,1002,Scania,2015-02-16 04:10:29.536728720,378400,rígido
2,1003,Volvo,2018-08-04 19:53:19.430278048,401246,articulado
3,1004,Mercedes,2020-03-30 00:56:07.355786368,174410,rígido
4,1005,Scania,2018-11-11 01:15:12.014872544,353975,rígido

In [50]:
veiculo.to_csv("C:/Users/mathe/Documents/projetos/Analise de dados/projeto-20/paranaiba-transportes/dataset/veiculos.csv", index=False)